//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNSRTCWindows.WindowsCalc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WindowsCalc.CalculatorServiceSoap")]
    public interface CalculatorServiceSoap {
        
        // CODEGEN: Generating message contract since element name AddResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        TNSRTCWindows.WindowsCalc.AddResponse Add(TNSRTCWindows.WindowsCalc.AddRequest request);
        
        // CODEGEN: Generating message contract since element name SubtractResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Subtract", ReplyAction="*")]
        TNSRTCWindows.WindowsCalc.SubtractResponse Subtract(TNSRTCWindows.WindowsCalc.SubtractRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add", Namespace="http://tempuri.org/", Order=0)]
        public TNSRTCWindows.WindowsCalc.AddRequestBody Body;
        
        public AddRequest() {
        }
        
        public AddRequest(TNSRTCWindows.WindowsCalc.AddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int a;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int b;
        
        public AddRequestBody() {
        }
        
        public AddRequestBody(int a, int b) {
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddResponse", Namespace="http://tempuri.org/", Order=0)]
        public TNSRTCWindows.WindowsCalc.AddResponseBody Body;
        
        public AddResponse() {
        }
        
        public AddResponse(TNSRTCWindows.WindowsCalc.AddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddResult;
        
        public AddResponseBody() {
        }
        
        public AddResponseBody(string AddResult) {
            this.AddResult = AddResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubtractRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Subtract", Namespace="http://tempuri.org/", Order=0)]
        public TNSRTCWindows.WindowsCalc.SubtractRequestBody Body;
        
        public SubtractRequest() {
        }
        
        public SubtractRequest(TNSRTCWindows.WindowsCalc.SubtractRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SubtractRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int a;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int b;
        
        public SubtractRequestBody() {
        }
        
        public SubtractRequestBody(int a, int b) {
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubtractResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubtractResponse", Namespace="http://tempuri.org/", Order=0)]
        public TNSRTCWindows.WindowsCalc.SubtractResponseBody Body;
        
        public SubtractResponse() {
        }
        
        public SubtractResponse(TNSRTCWindows.WindowsCalc.SubtractResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SubtractResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SubtractResult;
        
        public SubtractResponseBody() {
        }
        
        public SubtractResponseBody(string SubtractResult) {
            this.SubtractResult = SubtractResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculatorServiceSoapChannel : TNSRTCWindows.WindowsCalc.CalculatorServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorServiceSoapClient : System.ServiceModel.ClientBase<TNSRTCWindows.WindowsCalc.CalculatorServiceSoap>, TNSRTCWindows.WindowsCalc.CalculatorServiceSoap {
        
        public CalculatorServiceSoapClient() {
        }
        
        public CalculatorServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TNSRTCWindows.WindowsCalc.AddResponse TNSRTCWindows.WindowsCalc.CalculatorServiceSoap.Add(TNSRTCWindows.WindowsCalc.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public string Add(int a, int b) {
            TNSRTCWindows.WindowsCalc.AddRequest inValue = new TNSRTCWindows.WindowsCalc.AddRequest();
            inValue.Body = new TNSRTCWindows.WindowsCalc.AddRequestBody();
            inValue.Body.a = a;
            inValue.Body.b = b;
            TNSRTCWindows.WindowsCalc.AddResponse retVal = ((TNSRTCWindows.WindowsCalc.CalculatorServiceSoap)(this)).Add(inValue);
            return retVal.Body.AddResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TNSRTCWindows.WindowsCalc.SubtractResponse TNSRTCWindows.WindowsCalc.CalculatorServiceSoap.Subtract(TNSRTCWindows.WindowsCalc.SubtractRequest request) {
            return base.Channel.Subtract(request);
        }
        
        public string Subtract(int a, int b) {
            TNSRTCWindows.WindowsCalc.SubtractRequest inValue = new TNSRTCWindows.WindowsCalc.SubtractRequest();
            inValue.Body = new TNSRTCWindows.WindowsCalc.SubtractRequestBody();
            inValue.Body.a = a;
            inValue.Body.b = b;
            TNSRTCWindows.WindowsCalc.SubtractResponse retVal = ((TNSRTCWindows.WindowsCalc.CalculatorServiceSoap)(this)).Subtract(inValue);
            return retVal.Body.SubtractResult;
        }
    }
}
